Alias
Tsorion9/42sh pull request #13
Opened 2021-01-06 21:13 UTC by SoliddSnake

Реализованы builtins Alias и Unalias, а также api для хеш-таблиц (последнее - хедер t_hashtable.h)
Более подробное описание с ссылками на источники во вкладке Issues.

ИЛЬЯ: тебе чтоб получать alias нужно использовать функцию char	*alias_api_get_alias(char *key); из хедера t_hashalias.h

Прогонял валгриндом на маке и убунту

2021-01-06 22:37 UTC, ag95v2 requested changes
1) Залей, пожалуйста, это в ветку 42_unstable.

2) в этот PR попали изменения в несколько файлов из readline/completion. Ясное дело, к alias они отношения не имеют. Разбей, плз, на 2 PR, если это сильно разные фичи

3) hashtable.h - api выглядит немного перегруженным.
Если у нас есть такая функция static_hashalias_action то может просто оставить только такой api?
char *search(char *key), 
void insert(char *key, char *value), 
void delete(char *key) + print_table, если нужно?
Они под капотом будут юзать static_hashalias_action,  пользователь ничего не узнает. Очень хочется спрятать все ненужное от глаз читателя.

Имя hash_api_delete_hash_date выглядит очень странным, date - дата.

4) есть вопросы к hash_api_print_hash_table. Зачем она выводит приглашение и вообще почему зависит от readline?

5) hash_api_init_hash_data делает memalloc, а потом memset нулями. memalloc уже делает memset. И ты в обеих ветках if возвращаешь 1 и то же))

6) Мы с Артуром в 21sh решили, что непрошедший malloc обрабатывать в этом проекте нецелесообразно, можно юзать xmalloc, который будет завершать программу. Это может сильно сократить объем кода.

7) builtin alias предполагает в твоем случае, что в качестве аргументов передается несколько строк типа а = б
По-моему, там должна быть одна строка со знаком = посередине типа a=b, причем = должен быть не заэкранирован и вообще имя должно удовлетворять определенным условиям. Этот момент хорошо бы уточнить в стандарте.

2021-01-07 07:49 UTC, volkov7 commented
Я так понял, этот код будет совместим только с веткой dev, было бы неплохо сделать функционал совместимый с веткой 42_unstable, потому что там актуальная версия шелла

2021-01-07 08:09 UTC, volkov7 requested changes

2021-01-07 08:09 UTC, volkov7 commented on src/hashtable/hash_api_hash_function.c
> +	return ((unsigned int)hash);
Функция возвращает unsigned int, а в сигнатуре функции int. Еще не совсем нравится, что для вычисления используется unsigned long, а затем происходит сужающее преобразование, мне кажется, это нехорошо

2021-01-07 08:09 UTC, volkov7 commented on src/hashtable/hash_api_insert_hash_data.c
> +		free(new);
Тут не совсем логически верно, если для ключа память выделится, а для value нет, то мы очистим указатель new, а указатель для key потеряем -> утечка. Думаю правильней будет написать функцию, которая будет принимать элемент хэш-таблицы и очищать ненулевые поля, а затем сам выделенный элемент и возвращать статус EXIT_FAILURE

2021-01-07 08:29 UTC, closed without merging